#
# Copyright © 2021 Bedag Informatik AG
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
## Build Kusible
FROM golang AS build

#LABEL  \{% for tag in _dest['tags']|list %}
#  "tag.{{ tag }}.repository"="{{ _dest['namespace'] }}/{{ _dest['name'] }}" \
#  "tag.{{ tag }}.source"="{{ _source["name"] }}:{{ _source["tag"] }}" \
#  "tag.{{ tag }}.git.repo"="{{ git_repo }}" \
#  "tag.{{ tag }}.git.ref"="{{ git_ref }}" \
#  "tag.{{ tag }}.git.commit"="{{ git_commit }}" \
#{%- endfor %}
#  "maintainer"="{{ maintainer }}" 

WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o kusible .

## Actual Kusible COntainer 
FROM scratch
COPY --from=build /build/kusible /kusible
RUN chmod +x /kusible
CMD [ "kusible" ]